### PR TITLE
Rough implementation

### PR DESCRIPTION
**Pull request by geowurster**
@kapadia (and @sgillies if you're interested)

The `implement` branch roughly implements several commands and kind of supports feature sequences so take a look at it and let me know what you think.  The command below is about the only case I tested so explore with caution.

The general workflow here is that there's a starter command that is responsible for opening a file and passing GeoJSON features to the first worker command, which does some operation and passes the feature to the next command, etc., until it hits a writer command, which dumps the data to disk.  The `meta` object is updated at each step so the final writer should know the output geometry, CRS, etc.

This command covers the use case outlined in https://github.com/mapbox/rasterio/issues/448:

```console
IMG=LC80160332015204LGN00_B5.TIF
$ rio shapes --sequence --sampling 100 --as-mask ${IMG} |\
    fio geoproc \
        cat -i - --sequence --crs $(rio info ${IMG} --crs) \
        simplify --tolerance 1 \
        reproject --dst-crs EPSG:4326 \
        load -o - --sequence |\
    fio collect |\
    geojsonio
```

Here's what's going on:

1. Extract a single feature representing the valid pixels in the Landsat scene and print as a feature sequence.  Decimate by a factor of 100 to speed up processing.
2. Catch the feature sequence from stdin in `fio geoproc` and push the data into the pipeline with `fio geoproc cat`.
3. Run a simplify to generalize the geometry.
4. Reproject the geometry to `EPSG:4326`.
5. Save the feature stream to an output datasource - in this case we're just writing the stream to stdout

There's definitely a lot that can be done with chaining these commands together and I suspect we can get it parallelized.  I'm not completely sold on using `cat` and `load` as the start and end of the pipelines - seems like `cat` should behave exactly like `fio cat`.  Might switch to `open` and `save` like the [click example](https://github.com/mitsuhiko/click/blob/master/examples/imagepipe/imagepipe.py).

Bonus points: it uses click plugins so people can write their own `fio-geoprocessing` plugins just like plugins for `fio`.

Also relates to https://github.com/Toblerity/Fiona/issues/173.

### CODE REVIEW

**Comment by kapadia** [comment]
@geowurster The example works great. Thanks for developing this so quickly. A few questions:

 * This only seems to work when using the `--sequence` option. Is there a fundamental limitation to only operate on feature collections?
 * Any chance we can drop the `-o` flag? The default behavior throughout `rio` is to print to stdout. Should someone want to write a file, `> file.geojson` seems appropriate. Just thinking of ways to make this less verbose.
 * How does `simplify` know to preserve the topology? Is this an assumption? Is my use case general enough that this assumption is appropriate for other use cases?

One more obtuse question:

 * What's the purpose of `fio geoproc`, as opposed to chaining individual commands (e.g. something like `fio simplify file.geojson | fio simplify | fio load | fio do-everything-for-me-please`? Are we aiming to do all operations at once with only one run of JSON serialization/deserialization?

Thanks again for setting up this example!

**Comment by geowurster** [comment]
@kapadia It's good to finally have a reason to explore command chaining.

- It should work on any Fiona supported datasource in addition to feature sequences, but I only barely tested anything so there coul be a bug.  Not sure if Fiona handles full GeoJSON from stdin if that's what you're trying.

```console
$ rio shapes --sampling 100 --as-mask ${IMG} > rectangle.geojson
$ fio geoproc cat -i rectangle.geojson simplify ...
```

- Preserve topology should have been on by default just like [shapely](http://toblerity.org/shapely/manual.html#object.simplify) but I forgot to set the default to True.  It's fixed now.  See `fio geoproc simplify --help`.

- I think having a `geojson` specific save command might be the best way to handle GeoJSON, so it could look more like the command below.  See below for how I see `fio geoproc` functioning.

```console
fio cat -i ${INFILE} simplify --tolerance 1 geojson --sequence
```

The primary arguments for `fio geoproc` over a bunch of subcommands like `fio simplify | fio buffer | fio whatever` are:

1. No JSON de/serialization between every step.
2. I think its a little more organized rather than dumping a ton of plugin commands on `fio`.
3. This can probably be parallelized with `multiprocessing.Pool.imap_unordered()` for a huge performance boost on large datasets, which is what I did for `fio buffer`.
4. The `fio geoproc` sub-group is pluggable, so developing very use-case specific steps would be trivial and can probably just inherit the parallelized boost.
5. Each command updates the `meta` object so you don't need a ton of flags on the output file to specify geometry type, CRS, etc.

That said, I'm not super thrilled about the UI and command composition, but I think that may be alleviated by adopting the Unix Philosophy and having each command do only one thing.  For instance, the `fio buffer` plugin handles reprojecting geometries before and after buffering, but the `fio geoproc buffer` command does not.  The idea being that if you want to reproject you can just drop a `reproject` command in the stream wherever you want.

At this point I'm just kind of exploring what's possible here and welcome any feedback.

**Comment by sgillies** [comment]
@geowurster I have an old branch in https://github.com/Toblerity/Fiona/tree/sequence-processing where I dabbled a bit along the lines of https://github.com/mitsuhiko/click/tree/master/examples/imagepipe. I was hoping to find a way to make commands that could be used both in a normal unix pipeline *or* chained in the same process without any GeoJSON serialization, but didn't make it as far as you have. Do you think such a thing is feasible? Worth doing?

**Comment by geowurster** [comment]
@sgillies This implementation is exactly the same as `imagepipe`, but it doesn't feel very refined.  I don't yet have a very firm grasp on exactly how `group.resultscallback()` works and the requirements for a `@generator` or `@processor`, but it seems like there's probably a better way to structure the commands.

**Short Story**

I _think_ its possible.

**Long Story**

I experimented with this a little bit a few months ago and don't recall getting anywhere, but the hard part about this is probably probably figuring out how to let them be at the front of the pipeline and in the middle.  For instance, if `fio bounds` starts a pipeline it has to be able to read a file, do its job, and generate features, but if it is just a command somewhere in the chain it needs to accept a stream of features, do its job, and pass the features on to the next step.  The `@generator` and `@processor` syntax that `imagepipe` uses may not allow us to do that, but there's probably another way to stitch it all together.

I'm also not sure how to handle writing.  Most of the commands currently write to `stdout`, but figuring out to incorporate some `save` style commands could be useful for sending data to datastore or other format.  One option is to just pipe the results of the pipeline to `fio load` or `fio postgres` or something, except that now there are commands registered that can't be incorporated directly into the pipeline.

**Comment by kapadia** [comment]
@geowurster Thanks for clarifying my questions. I think you're on to something very powerful. It sounds like you need most help in ironing out an interface. Perhaps as a prerequisite we need to get Fiona up to speed with CLI command chaining (https://github.com/Toblerity/Fiona/issues/173).

I'm happy to put a few cycles to build these features. You and @sgillies are more informed in these workflows than I, so I concede to you on what's best to implement first.

**Comment by geowurster** [comment]
@kapadia @sgillies I agree, this seems pretty powerful and worth exploring.

I think the first step is to implement a stripped down version of `fio` to determine if we can let the commands behave as they do now and still operate as a chained pipeline.  Do we want a separate repo where we can test that out, or I'm happy to host that here on branches?

The big question I have is how we get features into and out of a pipeline.  In other words, can we do:

```console
$ fio cat ${INFILE} buffer --dist 100 simplify --tolerance 1 load ${OUTFILE}
```

Instead of:

```console
$ fio cat ${INFILE} | fio buffer --dist 100 simplify --tolerance | fio load ${OUTFILE}
```

There are some internal benefits to the first method, and I think in the long term its more flexible, but I expect it to be more difficult to implement.

**Pull request closed without merging**
